/* PollinationPro — Copyright (C) 2026 Luis Ángel Barrera-Guzmán.
   Free software under the GNU General Public License, version 3; see LICENSE. */
/* PollinationPro — practice data, generated by the program.

   Every record here is FICTIONAL: drawn with a seeded generator around
   invented centres, with invented phenologies, and marked as such in its
   dataset name. The taxa are real names so the example reads like a real
   study, but no point, date or count reproduces an actual observation, and
   none may be cited as one. They carry deliberate errors (duplicates, a
   (0, 0), swapped coordinates, a longitude without its sign, the centroid of
   the country, rounded coordinates, a date in the future, cultivated plants)
   so that Block 3 has something to find.

   Two practice studies:
     · 'cucurbits' — five Sechium species and Cucurbita with squash bees and
       the honey bee, in Mexico;
     · 'coffee' — Coffea arabica with the honey bee and stingless bees, in
       southern Mexico and Central America.

   And a set of fictional environmental layers (present and future) for
   Blocks 7 and 8, built from rules, not from any climate database. */

const Examples = {};

(function () {
  const DATASET = { es: 'Ejemplo ficticio de PollinationPro', en: 'PollinationPro fictional example' };

  /* each taxon: centres [lon, lat, sdLon, sdLat, weight], flowering/flight
     peak (day of year) and spread (days), share of cultivated records, n */
  const STUDIES = {
    cucurbits: {
      preset: 'cucurbits',
      plants: [
        { name: 'Sechium edule', n: 420, cult: 0.3, peak: 250, sd: 45, elev: [800, 2200], centres: [[-97.0, 19.3, 0.6, 0.5, 3], [-96.7, 17.1, 0.8, 0.5, 2], [-92.8, 16.6, 0.8, 0.5, 2], [-98.2, 19.0, 0.5, 0.4, 2], [-99.3, 19.3, 0.6, 0.5, 1]] },
        { name: 'Sechium compositum', n: 70, cult: 0, peak: 270, sd: 30, elev: [300, 1500], centres: [[-92.3, 15.3, 0.4, 0.3, 1], [-92.9, 16.7, 0.4, 0.3, 1]] },
        { name: 'Sechium chinantlense', n: 45, cult: 0, peak: 240, sd: 30, elev: [100, 900], centres: [[-96.2, 17.7, 0.3, 0.25, 1]] },
        { name: 'Sechium hintonii', n: 40, cult: 0, peak: 255, sd: 28, elev: [900, 1800], centres: [[-100.1, 18.7, 0.4, 0.3, 1]] },
        { name: 'Sechium mexicanum', n: 35, cult: 0, peak: 265, sd: 32, elev: [900, 2000], centres: [[-102.1, 19.2, 0.5, 0.3, 1]] },
        { name: 'Cucurbita', n: 600, cult: 0.35, peak: 225, sd: 50, elev: [0, 2500], centres: [[-99.0, 19.5, 2.2, 1.6, 3], [-103.3, 20.6, 1.5, 1.0, 1], [-106.0, 25.0, 2.0, 2.0, 1], [-92.5, 16.8, 1.0, 0.7, 1], [-89.5, 20.5, 0.8, 0.5, 1]] },
      ],
      polls: [
        { name: 'Xenoglossa gabbii', n: 60, peak: 215, sd: 35, centres: [[-99.5, 19.6, 1.8, 1.2, 1], [-103.5, 21.0, 1.2, 0.8, 1]] },
        { name: 'Xenoglossa mustelina', n: 45, peak: 225, sd: 30, centres: [[-104.8, 23.5, 1.5, 1.5, 1]] },
        { name: 'Peponapis crassidentata', n: 90, peak: 230, sd: 40, centres: [[-97.4, 19.1, 1.0, 0.8, 2], [-96.5, 17.2, 0.8, 0.6, 1], [-92.8, 16.4, 0.9, 0.6, 1]] },
        { name: 'Peponapis azteca', n: 70, peak: 240, sd: 38, centres: [[-99.1, 19.4, 1.1, 0.9, 1], [-101.5, 19.8, 1.0, 0.7, 1]] },
        { name: 'Peponapis pruinosa', n: 55, peak: 205, sd: 30, centres: [[-106.5, 28.0, 2.0, 1.8, 1]] },
        { name: 'Apis mellifera', n: 700, peak: 120, sd: 120, centres: [[-99.0, 19.5, 2.5, 1.8, 3], [-103.3, 20.6, 1.8, 1.2, 1], [-89.6, 20.6, 1.0, 0.6, 1], [-96.9, 18.9, 1.2, 1.0, 1], [-106.4, 27.0, 2.5, 2.5, 1]] },
      ],
      visits: {
        sites: [['Huatusco, Ver.', -96.97, 19.15], ['Chinantla, Oax.', -96.2, 17.75], ['Comitán, Chis.', -92.13, 16.25], ['Temascaltepec, Méx.', -100.05, 19.0], ['Coalcomán, Mich.', -103.16, 18.78]],
        /* plant × visitor × expected visits per site-day */
        plants: ['Sechium edule', 'Sechium compositum', 'Sechium chinantlense', 'Sechium hintonii', 'Sechium mexicanum', 'Cucurbita pepo'],
        visitors: ['Apis mellifera', 'Trigona fulviventris', 'Partamona bilineata', 'Scaptotrigona mexicana', 'Peponapis crassidentata', 'Peponapis azteca', 'Xenoglossa gabbii', 'Bombus ephippiatus', 'Halictus ligatus', 'Polistes instabilis', 'Toxomerus marginatus'],
        rates: [
          [9, 3, 2, 2, 1.2, 0.6, 0.3, 0.8, 0.8, 0.5, 0.4],
          [3, 2.5, 3, 0.5, 0.4, 0, 0, 0, 0.6, 0.8, 0.2],
          [2, 3, 1.5, 0.3, 0.8, 0, 0, 0, 0.3, 0.2, 0.3],
          [4, 0.4, 0, 0.3, 0, 0.9, 0.2, 1.5, 0.8, 0.3, 0.2],
          [3, 0.2, 0, 0, 0, 0.7, 0.5, 1.0, 1.0, 0.6, 0.4],
          [6, 1, 0.5, 0.4, 6, 4, 3, 1.2, 1.0, 0.3, 0.5],
        ],
      },
    },
    coffee: {
      preset: 'coffee',
      plants: [
        { name: 'Coffea arabica', n: 500, cult: 0.97, peak: 75, sd: 25, elev: [600, 1700], centres: [[-96.9, 19.3, 0.5, 0.4, 3], [-92.3, 15.3, 0.6, 0.4, 3], [-90.8, 14.7, 0.6, 0.4, 2], [-86.5, 14.2, 0.9, 0.5, 2], [-84.0, 9.9, 0.4, 0.3, 1]] },
      ],
      polls: [
        { name: 'Apis mellifera', n: 700, peak: 90, sd: 110, centres: [[-96.9, 19.2, 1.5, 1.0, 2], [-92.5, 15.8, 1.2, 0.8, 2], [-89.0, 14.5, 1.5, 0.8, 2], [-84.5, 10.5, 1.0, 0.6, 1]] },
        { name: 'Trigona fulviventris', n: 180, peak: 110, sd: 90, centres: [[-92.5, 15.6, 1.2, 0.8, 2], [-88.5, 14.5, 1.5, 0.8, 2], [-84.2, 10.0, 0.8, 0.6, 1]] },
        { name: 'Melipona beecheii', n: 120, peak: 100, sd: 80, centres: [[-89.3, 20.3, 1.0, 0.6, 2], [-91.5, 16.0, 1.5, 1.0, 1]] },
        { name: 'Scaptotrigona mexicana', n: 110, peak: 95, sd: 85, centres: [[-97.3, 19.9, 0.6, 0.5, 2], [-96.9, 18.9, 0.6, 0.5, 1]] },
        { name: 'Partamona bilineata', n: 90, peak: 105, sd: 80, centres: [[-92.0, 15.2, 1.0, 0.6, 1], [-86.8, 14.0, 1.2, 0.6, 1]] },
      ],
      visits: {
        sites: [['Coatepec, Ver.', -96.96, 19.45], ['Tapachula, Chis.', -92.26, 14.9], ['Antigua, Guatemala', -90.73, 14.56], ['Marcala, Honduras', -88.02, 14.15]],
        plants: ['Coffea arabica'],
        visitors: ['Apis mellifera', 'Trigona fulviventris', 'Melipona beecheii', 'Scaptotrigona mexicana', 'Partamona bilineata', 'Plebeia frontalis', 'Nannotrigona perilampoides', 'Halictus ligatus', 'Syrphidae sp.'],
        rates: [[12, 4, 1.2, 3, 2, 1.5, 1, 0.8, 0.6]],
      },
    },
  };

  /* the genus → study-list entry of the preset: a record of Peponapis azteca
     belongs to the entry 'Peponapis' */
  function entryFor(list, name) {
    const n = name.toLowerCase();
    return list.find(t => t.name.toLowerCase() === n) || list.find(t => n.startsWith(t.name.toLowerCase() + ' '));
  }

  /* the state bounding box a point must fall in, to keep points on land */
  function onLand(lon, lat) {
    if (!window.GEO) return true;
    return !!(GEO.stateOf(lon, lat) || GEO.countryOf(lon, lat));
  }

  function build(id, taxa) {
    const S = STUDIES[id];
    const r = rng(id === 'cucurbits' ? 20260927 : 20260928);
    const records = [];
    let k = 0;
    const draw = (sp, role) => {
      const t = entryFor(taxa, sp.name);
      if (!t) return;
      const tot = sp.centres.reduce((a, c) => a + c[4], 0);
      let made = 0, guard = 0;
      while (made < sp.n && guard++ < sp.n * 30) {
        /* a centre, by weight */
        let u = r() * tot, c = sp.centres[0];
        for (const cc of sp.centres) { u -= cc[4]; if (u <= 0) { c = cc; break; } }
        const lon = +(c[0] + c[2] * randn(r)).toFixed(5), lat = +(c[1] + c[3] * randn(r)).toFixed(5);
        if (!onLand(lon, lat)) continue;
        /* a date around the peak; the bees' records follow the field seasons of collectors a little */
        let day = Math.round(sp.peak + sp.sd * randn(r));
        day = ((day - 1) % 365 + 365) % 365 + 1;
        const y = 1975 + Math.floor(r() * 50);
        const dt = fromDoy(2025, day);
        const cult = role === 'plant' && r() < (sp.cult || 0);
        const st = window.GEO ? GEO.stateOf(lon, lat) : null, ct = window.GEO ? GEO.countryOf(lon, lat) : null;
        const basis = role === 'plant' ? (r() < 0.55 ? 'PRESERVED_SPECIMEN' : 'HUMAN_OBSERVATION') : (r() < 0.6 ? 'PRESERVED_SPECIMEN' : 'HUMAN_OBSERVATION');
        records.push({
          id: 'x' + (++k), src: 'example', taxonId: t.id, role,
          name: sp.name, species: sp.name.split(' ').length > 1 ? sp.name : '', genus: sp.name.split(' ')[0], family: role === 'plant' ? (sp.name.startsWith('Coffea') ? 'Rubiaceae' : 'Cucurbitaceae') : 'Apidae',
          rank: sp.name.split(' ').length > 1 ? 'SPECIES' : 'GENUS', infra: '',
          lat, lon, unc: r() < 0.3 ? null : Math.round(Math.exp(4 + 3 * r())), elev: sp.elev && r() < 0.5 ? Math.round(sp.elev[0] + (sp.elev[1] - sp.elev[0]) * r()) : null,
          cc: ct ? ct.a2 : '', country: ct ? ct.a2 : '', stateProvince: st ? st.name : '', locality: cult ? (r() < 0.5 ? T('cultivado en traspatio', 'cultivated in a backyard') : T('huerto familiar', 'home garden')) : '',
          y: r() < 0.97 ? y : null, m: dt.m, d: r() < 0.9 ? dt.d : null, eventDate: '',
          basis, inst: role === 'plant' ? ['MEXU', 'XAL', 'ENCB', 'IEB'][Math.floor(r() * 4)] : ['CNIN', 'EMEC', 'UNAM', 'ECOSUR'][Math.floor(r() * 4)],
          dataset: DATASET[I18N.lang], datasetKey: '', license: '', recordedBy: '',
          estab: cult && r() < 0.5 ? 'MANAGED' : '', repro: role === 'plant' && r() < 0.4 ? 'flowering' : '', sex: role === 'poll' && r() < 0.5 ? (r() < 0.5 ? 'MALE' : 'FEMALE') : '', lifeStage: '',
          remarks: cult && r() < 0.5 ? T('planta sembrada', 'planted') : '', issues: '',
        });
        made++;
      }
    };
    S.plants.forEach(sp => draw(sp, 'plant'));
    S.polls.forEach(sp => draw(sp, 'poll'));

    /* ---- the seeded errors, each on a known record so the tests can find it ---- */
    const pick = i => records[Math.floor(i * records.length)];
    const clone = o => ({ ...o, id: 'x' + (++k) });
    for (let i = 0; i < 18; i++) records.push(clone(pick((i * 0.137) % 1)));                 // exact duplicates
    const e1 = pick(0.21); e1.lat = 0; e1.lon = 0; e1._seed = 'zero';
    const e2 = pick(0.33); [e2.lat, e2.lon] = [e2.lon, e2.lat]; e2._seed = 'swapped';
    const e3 = pick(0.47); e3.lon = Math.abs(e3.lon); e3._seed = 'unsigned';
    const e4 = pick(0.58); e4.lat = 23.6345; e4.lon = -102.5528; e4._seed = 'centroid';      // the centroid of Mexico
    const e5 = pick(0.66); e5.lat = Math.round(e5.lat); e5.lon = Math.round(e5.lon); e5._seed = 'rounded';
    const e6 = pick(0.74); e6.y = 2031; e6._seed = 'future';
    const e7 = pick(0.81); e7.unc = 25000; e7._seed = 'imprecise';
    return records;
  }

  /* the visit table: sites × plant × visitor, drawn from Poisson counts */
  function visits(id) {
    const V = STUDIES[id].visits;
    const r = rng(id === 'cucurbits' ? 77 : 78);
    const pois = lam => { let L = Math.exp(-lam), p = 1, k = 0; do { k++; p *= r(); } while (p > L); return k - 1; };
    const out = [];
    V.sites.forEach(([site, lon, lat], si) => {
      V.plants.forEach((pl, pi) => {
        /* not every plant grows at every site */
        if (V.plants.length > 1 && (pi + si) % 3 === 1 && pi !== 0) return;
        for (let day = 0; day < 3; day++) {
          V.visitors.forEach((vi, vj) => {
            const lam = V.rates[pi][vj] * (0.5 + r());
            const n = pois(lam);
            if (!n) return;
            const date = fromDoy(2025, 230 + day * 9 + si * 3);
            out.push({ plant: pl, visitor: vi, n, site, lon, lat, y: 2025, m: date.m, d: date.d, src: 'example', type: 'visit', ref: DATASET[I18N.lang] });
          });
        }
      });
    });
    return out;
  }

  /* ---- practice layers ----
     Four FICTIONAL layers over Mexico and Central America (0.1°, the land of
     the program's own outlines), so that Blocks 7 and 8 can be learned without
     downloading anything: an invented relief made of smooth ridges and a
     plateau, and three climate variables derived from it and from latitude
     with simple rules (cooler with height and towards the north, wetter to the
     south-east and on the Gulf slope). They look like a climate but are not
     one: no value reproduces a measurement. The 'future' set warms and dries
     them by rules too. Each layer comes back as an ESRI ASCII grid, the text
     format any GIS reads, so they go through the same reader as the user's. */
  const LAYER_BOX = { x0: -118, y0: 33, dx: 0.1, w: 360, h: 260 };
  const bump = (lon, lat, cx, cy, sx, sy) => Math.exp(-(((lon - cx) / sx) ** 2) - (((lat - cy) / sy) ** 2));
  /* a ridge: a Gaussian around the segment (ax, ay)–(bx, by) */
  function ridge(lon, lat, ax, ay, bx, by, width) {
    const vx = bx - ax, vy = by - ay, t = Math.max(0, Math.min(1, ((lon - ax) * vx + (lat - ay) * vy) / (vx * vx + vy * vy)));
    const dx = lon - (ax + t * vx), dy = lat - (ay + t * vy);
    return Math.exp(-(dx * dx + dy * dy) / (width * width));
  }
  function relief(lon, lat) {
    return 1900 * bump(lon, lat, -101.8, 22.5, 3.2, 3.6)          // the central plateau
      + 1300 * ridge(lon, lat, -108.8, 29.5, -103.6, 21.4, 1.0)    // western sierra
      + 1100 * ridge(lon, lat, -100.8, 25.8, -97.6, 19.9, 0.8)     // eastern sierra
      + 1000 * ridge(lon, lat, -104.6, 19.5, -97.0, 19.1, 0.55)    // volcanic belt
      + 1200 * ridge(lon, lat, -101.8, 18.2, -96.0, 16.8, 0.7)     // southern sierra
      + 1500 * bump(lon, lat, -92.4, 16.4, 1.0, 0.6)               // highlands of the south-east
      + 1300 * ridge(lon, lat, -91.6, 15.0, -85.6, 13.8, 0.9)      // highlands of Central America
      + 1200 * bump(lon, lat, -84.0, 9.8, 0.8, 0.5)
      + 900 * ridge(lon, lat, -116.0, 32.0, -110.2, 23.8, 0.55);   // peninsular sierra
  }
  function climateAt(lon, lat, e, future) {
    const north = Math.max(0, lat - 16);
    let t = 29.2 - 0.0058 * e - 0.33 * north;
    let season = 140 + 20 * north + 0.09 * e + 90 * bump(lon, lat, -100.5, 21.5, 3.5, 2.5);   // BIO4 = sd of monthly means × 100; more inland
    const wet = 1 / (1 + Math.exp(-(0.28 * (21.0 - lat) + 0.34 * (lon + 100.0))));
    let p = 90 + 2300 * wet + 900 * bump(lon, lat, -97.1, 19.6, 0.7, 1.4) + 900 * bump(lon, lat, -93.0, 16.9, 1.3, 0.9) - 650 * bump(lon, lat, -101.5, 23.5, 2.8, 3.0);
    p = Math.max(70, p);
    if (future) { t += 1.8 + 0.05 * north; season *= 1.05; p *= 1 - 0.05 - 0.008 * north; }
    return { t, season, p };
  }
  const asc = (vals, dec) => {
    const B = LAYER_BOX, lines = [`ncols ${B.w}`, `nrows ${B.h}`, `xllcorner ${B.x0}`, `yllcorner ${B.y0 - B.h * B.dx}`, `cellsize ${B.dx}`, 'NODATA_value -9999'];
    for (let r = 0; r < B.h; r++) {
      const row = new Array(B.w);
      for (let c = 0; c < B.w; c++) { const v = vals[r * B.w + c]; row[c] = Number.isNaN(v) ? '-9999' : v.toFixed(dec); }
      lines.push(row.join(' '));
    }
    return lines.join('\n') + '\n';
  };
  /* kind: 'present' (BIO1, BIO4, BIO12 and the relief) or 'future' (the three climate layers) */
  function layers(kind) {
    const B = LAYER_BOX, n = B.w * B.h;
    const E = new Float32Array(n).fill(NaN), T1 = new Float32Array(n).fill(NaN), T4 = new Float32Array(n).fill(NaN), P = new Float32Array(n).fill(NaN);
    const r = rng(20260929);
    for (let row = 0; row < B.h; row++) {
      const lat = B.y0 - (row + 0.5) * B.dx;
      for (let c = 0; c < B.w; c++) {
        const lon = B.x0 + (c + 0.5) * B.dx;
        if (!window.GEO || !GEO.countryOf(lon, lat)) continue;
        const i = row * B.w + c;
        const e = Math.max(0, relief(lon, lat) + 60 * randn(r));
        const k = climateAt(lon, lat, e, kind === 'future');
        E[i] = e; T1[i] = k.t; T4[i] = k.season; P[i] = k.p;
      }
    }
    const tag = kind === 'future' ? 'practica_futuro_' : 'practica_';
    const out = [{ name: tag + 'bio_1.asc', text: asc(T1, 1) }, { name: tag + 'bio_4.asc', text: asc(T4, 0) }, { name: tag + 'bio_12.asc', text: asc(P, 0) }];
    if (kind !== 'future') out.push({ name: 'practica_altitud.asc', text: asc(E, 0) });
    return out;
  }

  Object.assign(Examples, { STUDIES, DATASET, build, visits, entryFor, layers, LAYER_BOX });
  window.Examples = Examples;
})();
