/* PollinationPro — Copyright (C) 2026 Luis Ángel Barrera-Guzmán.
   Free software under the GNU General Public License, version 3; see LICENSE. */
/* PollinationPro — Block 10: the report and the tables of the study.

   One self-contained HTML file: what each block computed, the figures inlined
   as SVG with their colours resolved, the methods written from what was
   actually run (a method that was not used is not described), the references
   of those methods only, the GBIF datasets that must be credited, and an
   appendix with every parameter, so the study can be repeated. It opens in
   any browser and prints to PDF.

     Report.build(opts)   → the HTML text
     Report.csvs()        → the tables of the study as .csv files
     Report.params()      → the calculation record, as a plain object
     Report.summary()     → the executive summary lines */

const Report = {};

(function () {
  const two = (es, en) => T(es, en);
  const f0 = v => (v == null || !isFinite(v) ? '—' : fmtNum(v, 0));
  const f2 = v => (v == null || !isFinite(v) ? '—' : fmtFixed(v, 2));
  const f3 = v => (v == null || !isFinite(v) ? '—' : fmtFixed(v, 3));
  const pc = v => (v == null || !isFinite(v) ? '—' : fmtPct(v, 0));
  const it = s => `<i>${esc(s)}</i>`;
  let figN = 0, tabN = 0, INC = null, CITED = null;
  const cite = (...keys) => { keys.forEach(k => CITED.add(k)); return keys.join('; '); };

  /* ---------------- pieces ---------------- */
  function table(cols, rows, caption) {
    tabN++;
    return `<table><caption>${two('Cuadro', 'Table')} ${tabN}. ${caption}</caption><thead><tr>${cols.map(c => `<th${c.num ? ' class="num"' : ''}>${c.label}</th>`).join('')}</tr></thead><tbody>` +
      rows.map(r => `<tr>${cols.map(c => { const v = c.get ? c.get(r) : r[c.key]; return `<td${c.num ? ' class="num"' : ''}>${v == null || v === '' ? '—' : v}</td>`; }).join('')}</tr>`).join('') + '</tbody></table>';
  }
  function figure(id, caption) {
    const svg = document.getElementById(id);
    if (!svg || svg.childElementCount <= 1) return '';
    figN++;
    const composed = Fig.compose(svg, { theme: 'light', background: 'white' });
    const xml = Fig.serialize(composed).replace(/^<\?xml[^>]*>\s*/, '').replace(/ width="\d+(\.\d+)?" height="\d+(\.\d+)?"/, '');
    return `<figure><div class="fig">${xml}</div><figcaption>${two('Figura', 'Figure')} ${figN}. ${caption}</figcaption></figure>`;
  }
  const p = s => (s ? `<p>${s}</p>` : '');
  const kv = pairs => `<dl class="kv">${pairs.filter(x => x && x[1] != null && x[1] !== '').map(([k, v]) => `<dt>${k}</dt><dd>${v}</dd>`).join('')}</dl>`;
  const use = k => (!INC || INC[k] !== false);

  /* ---------------- 1 · data ---------------- */
  function secData() {
    const R = state.raw, bySrc = s => R.filter(r => r.src === s).length;
    let h = `<h2>1. ${two('Taxones y registros', 'Taxa and records')}</h2>`;
    const f = window.B2 ? B2.filters() : {};
    h += p(two(`La lista de estudio incluye ${state.taxa.filter(t => t.role === 'plant').length} plantas y ${state.taxa.filter(t => t.role === 'poll').length} visitantes. Se reunieron ${f0(R.length)} registros de presencia: ${f0(bySrc('gbif'))} de GBIF${bySrc('own') ? `, ${f0(bySrc('own'))} propios` : ''}${bySrc('example') ? `, ${f0(bySrc('example'))} FICTICIOS de práctica` : ''}. ${state.visits.length ? `Además, ${f0(state.visits.reduce((a, v) => a + v.n, 0))} visitas observadas en ${state.visits.length} registros de campo.` : ''} ${state.interactions.length ? `Se consultaron ${f0(state.interactions.length)} registros de interacciones publicadas.` : ''}`,
      `The study list includes ${state.taxa.filter(t => t.role === 'plant').length} plants and ${state.taxa.filter(t => t.role === 'poll').length} visitors. ${f0(R.length)} presence records were gathered: ${f0(bySrc('gbif'))} from GBIF${bySrc('own') ? `, ${f0(bySrc('own'))} own` : ''}${bySrc('example') ? `, ${f0(bySrc('example'))} FICTIONAL practice ones` : ''}. ${state.visits.length ? `In addition, ${f0(state.visits.reduce((a, v) => a + v.n, 0))} observed visits in ${state.visits.length} field records.` : ''} ${state.interactions.length ? `${f0(state.interactions.length)} published interaction records were consulted.` : ''}`));
    if (bySrc('example')) h += `<p class="warn">${two('Este informe contiene datos de práctica generados por el programa. No representan observaciones reales y no deben publicarse.', 'This report contains practice data generated by the program. They do not represent real observations and must not be published.')}</p>`;
    h += table([
      { label: two('Papel', 'Role'), get: t => two(...Taxa.ROLE[t.role]) },
      { label: two('Entrada', 'Entry'), get: t => it(Taxa.label(t)) },
      { label: two('Clave GBIF', 'GBIF key'), get: t => (t.key || '—') },
      { label: two('Registros', 'Records'), num: true, get: t => f0(R.filter(r => r.taxonId === t.id).length) },
      { label: two('En GBIF (con filtros)', 'In GBIF (filtered)'), num: true, get: t => (state.fetchMeta[t.id] ? f0(state.fetchMeta[t.id].total) : '—') },
      { label: two('Descarga', 'Download'), get: t => (state.fetchMeta[t.id] ? state.fetchMeta[t.id].date : '—') },
    ], state.taxa, two('Lista de estudio y registros reunidos', 'Study list and records gathered'));
    return h;
  }

  /* ---------------- 2 · cleaning ---------------- */
  function secClean() {
    const C = state.clean; if (!C) return '';
    const n0 = C.records.length + C.dropped.length;
    let h = `<h2>2. ${two('Depuración y taxonomía', 'Cleaning and taxonomy')}</h2>`;
    const used = Clean.RULES.filter(x => C.count[x.id].removed || (x.id === 'swapped' && C.fixes));
    h += p(two(`De ${f0(n0)} registros se conservaron ${f0(C.records.length)} (${pc(C.records.length / Math.max(1, n0))}). Unidad de análisis: ${C.params.unit === 'species' ? 'especie' : 'entrada de la lista'}.`, `Of ${f0(n0)} records, ${f0(C.records.length)} were kept (${pc(C.records.length / Math.max(1, n0))}). Unit of analysis: ${C.params.unit === 'species' ? 'species' : 'list entry'}.`));
    h += table([{ label: two('Regla', 'Rule'), get: x => two(...x.t) }, { label: two('Alcanzados', 'Reached'), num: true, get: x => f0(x.id === 'swapped' ? C.fixes : C.count[x.id].flagged) }, { label: two('Quitados', 'Removed'), num: true, get: x => f0(C.count[x.id].removed) }], used, two('Reglas de depuración que actuaron', 'Cleaning rules that acted'));
    const units = new Map(); C.records.forEach(r => { if (!units.has(r.unit)) units.set(r.unit, { unit: r.unit, role: r.role, n: 0 }); units.get(r.unit).n++; });
    h += table([{ label: two('Papel', 'Role'), get: u => two(...Taxa.ROLE[u.role]) }, { label: two('Unidad', 'Unit'), get: u => it(u.unit) }, { label: two('Registros depurados', 'Cleaned records'), num: true, get: u => f0(u.n) }], [...units.values()], two('Unidades de análisis', 'Units of analysis'));
    h += figure('b4Map', two('Registros depurados de plantas (círculos) y visitantes (triángulos).', 'Cleaned records of plants (circles) and visitors (triangles).'));
    return h;
  }

  /* ---------------- 3 · co-occurrence ---------------- */
  function secCooc() {
    const S = state.cooc; if (!S) return '';
    const P = S.res.pairs, o = S.opt;
    const vv = x => (o.adjust ? x.verdictAdj : x.verdict);
    const count = v => P.filter(x => vv(x) === v).length;
    let h = `<h2>3. ${two('Coocurrencia espacial', 'Spatial co-occurrence')}</h2>`;
    h += p(two(`Con celdas de ${o.size}° y un universo de ${f0(S.res.N)} celdas (${o.mode === 'land' ? 'toda la tierra de la extensión' : 'grupo objetivo: celdas con registros de cualquier taxón del estudio'}), de ${P.length} pares planta × visitante ${count('positive')} coincidieron más de lo esperado, ${count('negative')} menos, ${count('random')} al azar y ${count('unclassified')} quedaron sin clasificar${o.adjust ? ' (p ajustados por tasa de falsos descubrimientos)' : ''}.`,
      `With ${o.size}° cells and a universe of ${f0(S.res.N)} cells (${o.mode === 'land' ? 'all land in the extent' : 'target group: cells with records of any taxon of the study'}), of ${P.length} plant × visitor pairs ${count('positive')} coincided more than expected, ${count('negative')} less, ${count('random')} at random and ${count('unclassified')} were unclassified${o.adjust ? ' (p adjusted for the false discovery rate)' : ''}.`));
    const V = { positive: ['más', 'more'], negative: ['menos', 'less'], random: ['azar', 'random'], unclassified: ['s/c', 'n/c'] };
    h += table([{ label: two('Planta', 'Plant'), get: r => it(r.plant) }, { label: two('Visitante', 'Visitor'), get: r => it(r.visitor) }, { label: 'N₁', num: true, key: 'n1' }, { label: 'N₂', num: true, key: 'n2' }, { label: two('Compartidas', 'Shared'), num: true, key: 'shared' }, { label: two('Esperadas', 'Expected'), num: true, get: r => fmtFixed(r.exp, 1) }, { label: two('EEF', 'SES'), num: true, get: r => f2(r.ses) }, { label: 'p', num: true, get: r => fmtNum(Math.min(1, 2 * Math.min(r.pLe, r.pGe)), 3) }, { label: two('p aj.', 'adj. p'), num: true, get: r => (r.pAdj == null ? '—' : fmtNum(r.pAdj, 3)) }, { label: two('Veredicto', 'Verdict'), get: r => two(...V[vv(r)]) }],
      P, two('Prueba probabilística de coocurrencia por par', 'Probabilistic co-occurrence test by pair'));
    h += figure('b5Matrix', two('Tamaño estandarizado del efecto de la coocurrencia de cada par.', 'Standardised effect size of the co-occurrence of each pair.'));
    if (S.sensitivity) h += figure('b5Sens', two(`Sensibilidad del EEF al tamaño de celda: ${esc(S.sensitivity.pair.plant)} × ${esc(S.sensitivity.pair.visitor)}.`, `Sensitivity of the SES to the cell size: ${esc(S.sensitivity.pair.plant)} × ${esc(S.sensitivity.pair.visitor)}.`));
    if (S.nn) h += p(two(`Distancia al visitante más cercano (${esc(S.nn.pair.plant)} × ${esc(S.nn.pair.visitor)}): mediana ${fmtFixed(S.nn.median, 1)} km frente a ${fmtFixed(S.nn.nullMedian, 1)} km bajo el modelo nulo (${S.nn.nSim} simulaciones; p más cerca = ${fmtNum(S.nn.pCloser, 3)}, p más lejos = ${fmtNum(S.nn.pFarther, 3)}); ${pc(S.nn.within[1])} de los puntos de la planta tienen un registro del visitante a 10 km o menos.`,
      `Distance to the nearest visitor (${esc(S.nn.pair.plant)} × ${esc(S.nn.pair.visitor)}): median ${fmtFixed(S.nn.median, 1)} km against ${fmtFixed(S.nn.nullMedian, 1)} km under the null model (${S.nn.nSim} simulations; p closer = ${fmtNum(S.nn.pCloser, 3)}, p farther = ${fmtNum(S.nn.pFarther, 3)}); ${pc(S.nn.within[1])} of the plant points have a visitor record within 10 km.`));
    if (S.range) h += p(two(`Envolventes convexas: la planta ocupa ${f0(S.range.areaP)} km², el visitante ${f0(S.range.areaV)} km²; ${pc(S.range.coverP)} del área de la planta queda dentro del área del visitante.`, `Convex hulls: the plant covers ${f0(S.range.areaP)} km², the visitor ${f0(S.range.areaV)} km²; ${pc(S.range.coverP)} of the plant's area lies within the visitor's area.`));
    return h;
  }

  /* ---------------- 4 · phenology ---------------- */
  function secPheno() {
    const S = state.pheno; if (!S) return '';
    let h = `<h2>4. ${two('Fenología y altitud', 'Phenology and elevation')}</h2>`;
    h += p(two(`${f0(S.nDated)} registros con mes (${pc(S.nDated / Math.max(1, S.nAll))}); perfiles ${S.opt.corrected ? 'corregidos por el esfuerzo mensual del grupo objetivo' : 'sin corrección por esfuerzo'}${S.opt.flowersOnly ? '; en plantas, solo registros con flor' : ''}.`, `${f0(S.nDated)} records with a month (${pc(S.nDated / Math.max(1, S.nAll))}); profiles ${S.opt.corrected ? 'corrected by the monthly effort of the target group' : 'without effort correction'}${S.opt.flowersOnly ? '; for plants, only records with flowers' : ''}.`));
    h += table([{ label: two('Unidad', 'Unit'), get: u => it(u.unit) }, { label: 'n', num: true, key: 'n' }, { label: two('Fecha media', 'Mean date'), get: u => (u.meanDoy != null ? fmtDoy(u.meanDoy) : '—') }, { label: 'R̄', num: true, get: u => f2(u.R) }, { label: two('DE (días)', 'SD (days)'), num: true, get: u => (isFinite(u.sdDays) ? f0(u.sdDays) : '—') }, { label: 'Rayleigh p', num: true, get: u => (u.p != null ? fmtNum(u.p, 3) : '—') }],
      S.units, two('Estadística circular de las fechas de cada unidad', 'Circular statistics of the dates of each unit'));
    h += figure('b6Phenogram', two('Fenograma: proporción de registros por mes de cada unidad.', 'Phenogram: share of records per month of each unit.'));
    h += table([{ label: two('Planta', 'Plant'), get: r => it(r.plant) }, { label: two('Visitante', 'Visitor'), get: r => it(r.visitor) }, { label: 'D', num: true, get: r => f2(r.D) }, { label: 'I', num: true, get: r => f2(r.I) }, { label: 'O', num: true, get: r => f2(r.O) }, { label: two('Desfase (días)', 'Lag (days)'), num: true, get: r => f0(r.lag) }, { label: 'Watson–Williams p', num: true, get: r => (r.wwP == null ? '—' : fmtNum(r.wwP, 3)) }],
      S.pairs, two('Solapamiento fenológico de cada par', 'Phenological overlap of each pair'));
    h += figure('b6Rose', two(`Rosa circular del par ${S.sel ? esc(S.sel.plant) + ' × ' + esc(S.sel.visitor) : ''}.`, `Circular rose of the pair ${S.sel ? esc(S.sel.plant) + ' × ' + esc(S.sel.visitor) : ''}.`));
    if (S.elevation && S.elevation.units.length) h += table([{ label: two('Unidad', 'Unit'), get: u => it(u.unit) }, { label: 'n', num: true, key: 'n' }, { label: two('Mín.', 'Min'), num: true, get: u => f0(u.min) }, { label: two('Mediana', 'Median'), num: true, get: u => f0(u.med) }, { label: two('Máx.', 'Max'), num: true, get: u => f0(u.max) }], S.elevation.units, two('Altitud de los registros (m)', 'Elevation of the records (m)'));
    return h;
  }

  /* ---------------- 5 · niche ---------------- */
  function secNiche() {
    const S = state.niche; if (!S || !S.pair) return '';
    let h = `<h2>5. ${two('Nicho ambiental', 'Environmental niche')}</h2>`;
    if (S.practice) h += `<p class="warn"><b>${two('Capas de práctica.', 'Practice layers.')}</b> ${two('Este nicho se calculó con las capas FICTICIAS que genera el programa para aprender: los resultados no dicen nada sobre las especies y no deben publicarse.', 'This niche was computed with the FICTIONAL layers the program generates for learning: the results say nothing about the species and must not be published.')}</p>`;
    h += p(two(`Variables: ${S.layers.join(', ')}. Fondo: ${f0(S.nBg)} celdas ${S.bg === 'buffer' ? `a ${S.bufferKm} km o menos de los registros` : 'de toda el área de las capas'}. Los dos primeros componentes explican ${pc(S.explained[0] + S.explained[1])} de la varianza. Densidades ${S.corrected ? 'corregidas por el ambiente disponible' : 'de registros dentro del ambiente disponible'}.`, `Variables: ${S.layers.join(', ')}. Background: ${f0(S.nBg)} cells ${S.bg === 'buffer' ? `within ${S.bufferKm} km of the records` : 'of the whole area of the layers'}. The first two components explain ${pc(S.explained[0] + S.explained[1])} of the variance. Densities ${S.corrected ? 'corrected by the available environment' : 'of records within the available environment'}.`));
    const q = S.pair;
    h += p(two(`${it(q.plant)} y ${it(q.visitor)}: D = <b>${f3(q.D)}</b>, I = ${f3(q.I)}; prueba de equivalencia p = ${fmtNum(q.pEq, 3)} (${q.pEq < 0.05 ? 'los nichos no son equivalentes' : 'no se rechaza la equivalencia'}); prueba de similitud p = ${fmtNum(q.pSim, 3)} (${q.pSim < 0.05 ? 'más similares de lo que el ambiente explica' : 'no más similares que al azar'}); ${q.nRep} repeticiones.`,
      `${it(q.plant)} and ${it(q.visitor)}: D = <b>${f3(q.D)}</b>, I = ${f3(q.I)}; equivalency test p = ${fmtNum(q.pEq, 3)} (${q.pEq < 0.05 ? 'the niches are not equivalent' : 'equivalency not rejected'}); similarity test p = ${fmtNum(q.pSim, 3)} (${q.pSim < 0.05 ? 'more alike than the environment explains' : 'no more alike than chance'}); ${q.nRep} replicates.`));
    h += figure('b7Space', two('Nichos de la planta y del visitante en el plano de los dos primeros componentes del ambiente.', 'Niches of the plant and the visitor on the plane of the first two components of the environment.'));
    h += table([{ label: two('Planta', 'Plant'), get: r => it(r.plant) }, { label: two('Visitante', 'Visitor'), get: r => it(r.visitor) }, { label: 'D', num: true, get: r => f3(r.D) }, { label: 'I', num: true, get: r => f3(r.I) }], S.matrix, two('Solapamiento de nicho de todos los pares', 'Niche overlap of every pair'));
    if (S.univariate) h += table([{ label: two('Variable', 'Variable'), key: 'variable' }, { label: two('Mediana planta', 'Plant median'), num: true, get: r => fmtNum(r.medPlant, 3) }, { label: two('Mediana visitante', 'Visitor median'), num: true, get: r => fmtNum(r.medVisitor, 3) }, { label: 'D', num: true, get: r => f2(r.D) }], S.univariate, two('Solapamiento en cada variable', 'Overlap on each variable'));
    return h;
  }

  /* ---------------- 6 · distribution ---------------- */
  function secSdm() {
    const S = state.sdm; if (!S) return '';
    const K = { logistic: ['regresión logística con fondo (términos lineales y cuadráticos, penalización de cresta)', 'background logistic regression (linear and quadratic terms, ridge penalty)'], mahalanobis: ['distancia de Mahalanobis', 'Mahalanobis distance'], envelope: ['envolvente bioclimática', 'bioclimatic envelope'] };
    const R = { maxtss: ['máximo TSS', 'maximum TSS'], p10: ['10 % de presencias', '10th percentile of presences'], p0: ['presencia mínima', 'minimum presence'] };
    let h = `<h2>6. ${two('Distribución potencial y desajuste', 'Potential distribution and mismatch')}</h2>`;
    if (state.rasters && state.rasters.practice) h += `<p class="warn"><b>${two('Capas de práctica.', 'Practice layers.')}</b> ${two('Los modelos se ajustaron con las capas FICTICIAS del programa (y, si hay futuro, con el futuro de práctica): los mapas no dicen nada sobre las especies y no deben publicarse.', 'The models were fitted with the program’s FICTIONAL layers (and, if there is a future, with the practice future): the maps say nothing about the species and must not be published.')}</p>`;
    const A = S.area, pA = A[1] + A[3];
    h += p(two(`Modelo: ${two(...K[S.kind])}; umbral: ${two(...R[S.rule])}; fondo: ${S.bgMode === 'target' ? 'grupo objetivo' : 'toda el área'} (${f0(S.nBg)} celdas); variables ${S.layers.join(', ')}. De ${f0(pA)} km² idóneos para ${it(S.plant)}, ${pc(A[3] / Math.max(1, pA))} tienen al menos un visitante potencial idóneo y ${pc(A[1] / Math.max(1, pA))} (${f0(A[1])} km²) no tienen ninguno.`,
      `Model: ${two(...K[S.kind])}; threshold: ${two(...R[S.rule])}; background: ${S.bgMode === 'target' ? 'target group' : 'whole area'} (${f0(S.nBg)} cells); variables ${S.layers.join(', ')}. Of ${f0(pA)} km² suitable for ${it(S.plant)}, ${pc(A[3] / Math.max(1, pA))} have at least one suitable potential visitor and ${pc(A[1] / Math.max(1, pA))} (${f0(A[1])} km²) have none.`));
    h += table([{ label: two('Unidad', 'Unit'), get: r => it(r[0]) }, { label: two('Celdas', 'Cells'), num: true, get: r => r[1].n }, { label: 'AUC', num: true, get: r => f3(r[1].auc) }, { label: 'TSS', num: true, get: r => f3(r[1].tss) }, { label: two('Omisión', 'Omission'), num: true, get: r => pc(r[1].omission) }, { label: two('Umbral', 'Threshold'), num: true, get: r => f3(r[1].threshold) }],
      Object.entries(S.units), two('Evaluación por validación cruzada', 'Cross-validated evaluation'));
    h += figure('b8MapMM', two('Desajuste potencial: planta con y sin visitante idóneo.', 'Potential mismatch: plant with and without a suitable visitor.'));
    if (S.future) {
      const F = S.future.area, fA = F[1] + F[3];
      h += p(two(`Con el clima futuro elegido, el área idónea de la planta pasa de ${f0(pA)} a ${f0(fA)} km² y la fracción sin visitante potencial de ${pc(A[1] / Math.max(1, pA))} a ${pc(F[1] / Math.max(1, fA))}.`, `Under the chosen future climate, the plant's suitable area goes from ${f0(pA)} to ${f0(fA)} km² and the share without a potential visitor from ${pc(A[1] / Math.max(1, pA))} to ${pc(F[1] / Math.max(1, fA))}.`));
      h += figure('b8MapFut', two('Desajuste potencial con el clima futuro.', 'Potential mismatch under the future climate.'));
    }
    return h;
  }

  /* ---------------- 7 · network ---------------- */
  function secNet() {
    const S = state.network; if (!S) return '';
    let h = `<h2>7. ${two('Red de interacciones', 'Interaction network')}</h2>`;
    const src = [S.opt.own ? two('observaciones propias', 'own observations') : '', S.opt.pub ? two('interacciones publicadas', 'published interactions') : ''].filter(Boolean).join(two(' e ', ' and '));
    h += p(two(`Red de ${S.plants} plantas y ${S.visitors} visitantes a partir de ${src}: ${S.links} vínculos, ${f0(S.visits)} visitas, conectancia ${f3(S.connectance)}, anidamiento NODF ${fmtFixed(S.nodf, 1)}, especialización H₂′ ${f3(S.H2p)}, modularidad Q ${f3(S.Q)} (${S.modules} módulos).`, `Network of ${S.plants} plants and ${S.visitors} visitors from ${src}: ${S.links} links, ${f0(S.visits)} visits, connectance ${f3(S.connectance)}, nestedness NODF ${fmtFixed(S.nodf, 1)}, specialisation H₂′ ${f3(S.H2p)}, modularity Q ${f3(S.Q)} (${S.modules} modules).`));
    if (S.nulls) h += p(two(`Frente a ${S.nulls.n} redes nulas: NODF z = ${f2(S.nulls.nodf.z)}${S.nulls.h2 ? `; H₂′ z = ${f2(S.nulls.h2.z)}` : ''}; Q z = ${f2(S.nulls.q.z)}.`, `Against ${S.nulls.n} null networks: NODF z = ${f2(S.nulls.nodf.z)}${S.nulls.h2 ? `; H₂′ z = ${f2(S.nulls.h2.z)}` : ''}; Q z = ${f2(S.nulls.q.z)}.`));
    h += figure('b9Graph', two('Red bipartita planta–visitante; el color indica el módulo y el grosor, el número de visitas.', 'Bipartite plant–visitor network; colour marks the module and width the number of visits.'));
    h += table([{ label: two('Visitante', 'Visitor'), get: r => it(r.name) }, { label: two('Visitas', 'Visits'), num: true, key: 'visits' }, { label: two('Grado', 'Degree'), num: true, key: 'degree' }, { label: two('Fuerza', 'Strength'), num: true, get: r => f2(r.strength) }, { label: "d′", num: true, get: r => f2(r.dprime) }],
      S.species.visitors.slice().sort((a, b) => b.strength - a.strength), two('Visitantes de la red', 'Visitors of the network'));
    if (S.focusCompleteness) { const c = S.focusCompleteness; h += p(two(`Visitantes de ${it(c.plant)}: ${c.S} registrados en ${f0(c.N)} visitas; Chao1 = ${fmtFixed(c.chao1, 1)} (completitud ${pc(c.completeness)}, cobertura ${pc(c.coverage)}).`, `Visitors of ${it(c.plant)}: ${c.S} recorded in ${f0(c.N)} visits; Chao1 = ${fmtFixed(c.chao1, 1)} (completeness ${pc(c.completeness)}, coverage ${pc(c.coverage)}).`)); h += figure('b9Rare', two('Curva de rarefacción de visitantes.', 'Visitor rarefaction curve.')); }
    return h;
  }

  /* ---------------- methods, written from what ran ---------------- */
  function methods() {
    const M = [];
    const C = state.clean;
    M.push(two(`Los registros de presencia se obtuvieron de GBIF mediante su interfaz de programación, con coordenadas y filtrados por país${state.raw.some(r => r.src === 'own') ? ', y se complementaron con registros propios' : ''} (${cite('Graham et al. 2004')}).`, `Presence records were obtained from GBIF through its programming interface, with coordinates and filtered by country${state.raw.some(r => r.src === 'own') ? ', and complemented with own records' : ''} (${cite('Graham et al. 2004')}).`));
    if (C) M.push(two(`Se depuraron con reglas de coordenadas imposibles, de centroides de país y de estado (dos definiciones, a ${C.params.centroidKm} km), coordenadas invertidas o sin signo detectadas contra el país declarado, incertidumbre mayor de ${C.params.maxUncKm} km, duplicados, fechas imposibles, fósiles y colecciones vivas${C.count.cultivated.removed ? ' y plantas cultivadas' : ''} (${cite('Chapman 2005', 'Zizka et al. 2020')}).${(C.params.synonyms || []).some(s => s.on) ? ` Se aplicó la reclasificación de Freitas et al. (2023) que sitúa a Peponapis como subgénero de Xenoglossa (${cite('Freitas et al. 2023')}).` : ''}`, `They were cleaned with rules for impossible coordinates, country and state centroids (two definitions, at ${C.params.centroidKm} km), swapped or unsigned coordinates detected against the stated country, uncertainty above ${C.params.maxUncKm} km, duplicates, impossible dates, fossils and living collections${C.count.cultivated.removed ? ' and cultivated plants' : ''} (${cite('Chapman 2005', 'Zizka et al. 2020')}).${(C.params.synonyms || []).some(s => s.on) ? ` The reclassification of Freitas et al. (2023) placing Peponapis as a subgenus of Xenoglossa was applied (${cite('Freitas et al. 2023')}).` : ''}`));
    if (state.cooc && use('cooc')) M.push(two(`La coocurrencia espacial de cada par planta × visitante se evaluó con el modelo probabilístico de Veech (${cite('Veech 2013')}) en celdas de ${state.cooc.opt.size}°, con el universo restringido a las celdas del grupo objetivo para descontar el sesgo de muestreo (${cite('Phillips et al. 2009')}); los valores p se ajustaron por la tasa de falsos descubrimientos (${cite('Benjamini & Hochberg 1995')}). Se comprobó la sensibilidad al tamaño de celda, se comparó la distancia al vecino más cercano con un modelo nulo de Monte Carlo (${cite('Davison & Hinkley 1997')}) y se midió el solapamiento de las envolventes convexas (${cite('Andrew 1979', 'Chamberlain & Duquette 2007')}).`, `The spatial co-occurrence of each plant × visitor pair was evaluated with Veech's probabilistic model (${cite('Veech 2013')}) on ${state.cooc.opt.size}° cells, with the universe restricted to the cells of the target group to discount sampling bias (${cite('Phillips et al. 2009')}); p-values were adjusted for the false discovery rate (${cite('Benjamini & Hochberg 1995')}). The sensitivity to the cell size was checked, the nearest-neighbour distance was compared with a Monte Carlo null model (${cite('Davison & Hinkley 1997')}) and the overlap of the convex hulls was measured (${cite('Andrew 1979', 'Chamberlain & Duquette 2007')}).`));
    if (state.pheno && use('pheno')) M.push(two(`Las fechas se analizaron con estadística circular: dirección media, longitud del vector medio y prueba de Rayleigh para cada unidad, y prueba de Watson–Williams entre planta y visitante (${cite('Batschelet 1981', 'Zar 2010', 'Fisher 1993')}); el solapamiento de los perfiles mensuales se midió con la D de Schoener, la I de Warren y el índice de Pianka (${cite('Schoener 1968', 'Warren et al. 2008', 'Pianka 1973')}).`, `Dates were analysed with circular statistics: mean direction, mean resultant length and Rayleigh test for each unit, and Watson–Williams test between plant and visitor (${cite('Batschelet 1981', 'Zar 2010', 'Fisher 1993')}); overlap of the monthly profiles was measured with Schoener's D, Warren's I and Pianka's index (${cite('Schoener 1968', 'Warren et al. 2008', 'Pianka 1973')}).`));
    if (state.niche && state.niche.pair && use('niche')) M.push(two(`El nicho ambiental se comparó en el espacio de los dos primeros componentes principales del ambiente de fondo, con densidades de kernel (${cite('Silverman 1986')}), la D de Schoener y las pruebas de equivalencia y similitud (${cite('Broennimann et al. 2012', 'Warren et al. 2008')}).`, `The environmental niche was compared in the space of the first two principal components of the background environment, with kernel densities (${cite('Silverman 1986')}), Schoener's D and the equivalency and similarity tests (${cite('Broennimann et al. 2012', 'Warren et al. 2008')}).`));
    if (state.sdm && use('sdm')) M.push(two(`La distribución potencial de cada unidad se estimó con ${state.sdm.kind === 'logistic' ? 'regresión logística contra el fondo' : state.sdm.kind === 'mahalanobis' ? 'la distancia de Mahalanobis' : 'una envolvente bioclimática'} (${cite(...(state.sdm.kind === 'logistic' ? ['Phillips et al. 2009'] : state.sdm.kind === 'mahalanobis' ? ['Farber & Kadmon 2003'] : ['Nix 1986']))}), evaluada por validación cruzada con AUC y TSS (${cite('Allouche et al. 2006', 'Lobo et al. 2008')}); el desajuste espacial se definió como el área idónea para la planta y para ningún visitante potencial (${cite('Schweiger et al. 2008')}).`, `The potential distribution of each unit was estimated with ${state.sdm.kind === 'logistic' ? 'logistic regression against the background' : state.sdm.kind === 'mahalanobis' ? 'the Mahalanobis distance' : 'a bioclimatic envelope'} (${cite(...(state.sdm.kind === 'logistic' ? ['Phillips et al. 2009'] : state.sdm.kind === 'mahalanobis' ? ['Farber & Kadmon 2003'] : ['Nix 1986']))}), evaluated by cross-validation with AUC and TSS (${cite('Allouche et al. 2006', 'Lobo et al. 2008')}); spatial mismatch was defined as the area suitable for the plant and for no potential visitor (${cite('Schweiger et al. 2008')}).`));
    if (state.network && use('network')) M.push(two(`La red de interacción se describió con la conectancia, el anidamiento NODF (${cite('Almeida-Neto et al. 2008')}), la especialización H₂′ y d′ (${cite('Blüthgen et al. 2006')}), la fuerza de especie (${cite('Bascompte et al. 2006')}) y la modularidad bipartita (${cite('Barber 2007', 'Beckett 2016')})${state.network.nulls ? `, comparadas con modelos nulos (${cite('Strona et al. 2014', 'Patefield 1981')})` : ''}${state.network.focusCompleteness ? `; la completitud del muestreo se estimó con Chao1 y rarefacción (${cite('Chao 1987', 'Hurlbert 1971')})` : ''}.`, `The interaction network was described with connectance, NODF nestedness (${cite('Almeida-Neto et al. 2008')}), H₂′ and d′ specialisation (${cite('Blüthgen et al. 2006')}), species strength (${cite('Bascompte et al. 2006')}) and bipartite modularity (${cite('Barber 2007', 'Beckett 2016')})${state.network.nulls ? `, compared with null models (${cite('Strona et al. 2014', 'Patefield 1981')})` : ''}${state.network.focusCompleteness ? `; sampling completeness was estimated with Chao1 and rarefaction (${cite('Chao 1987', 'Hurlbert 1971')})` : ''}.`));
    M.push(two(`Todos los análisis se realizaron con PollinationPro ${APP_VERSION}.`, `All analyses were carried out with PollinationPro ${APP_VERSION}.`));
    return M;
  }

  /* the GBIF datasets that contributed cleaned records: GBIF asks for each to be credited */
  function datasets() {
    const m = new Map();
    (state.clean ? state.clean.records : state.raw).filter(r => r.src === 'gbif').forEach(r => { const k = r.datasetKey || r.dataset; if (!m.has(k)) m.set(k, { key: r.datasetKey, name: r.dataset, license: r.license, n: 0 }); m.get(k).n++; });
    return [...m.values()].sort((a, b) => b.n - a.n);
  }

  /* ---------------- the whole report ---------------- */
  function build(opts) {
    const o = opts || {};
    INC = o.include || null; figN = 0; tabN = 0; CITED = new Set();
    const title = o.title || two('Plantas, polinizadores y su solapamiento', 'Plants, pollinators and their overlap');
    let body = '';
    body += secData();
    if (use('clean')) body += secClean();
    if (use('cooc')) body += secCooc();
    if (use('pheno')) body += secPheno();
    if (use('niche')) body += secNiche();
    if (use('sdm')) body += secSdm();
    if (use('network')) body += secNet();
    const meth = methods();
    const refs = (window.Home ? Home.REFS : []).filter(r => CITED.has(r[1])).sort((a, b) => a[1].localeCompare(b[1]));
    const ds = datasets();
    let tail = `<h2>${two('Métodos', 'Methods')}</h2>` + meth.map(p).join('');
    if (ds.length) {
      tail += `<h2>${two('Conjuntos de datos de GBIF', 'GBIF datasets')}</h2>` + p(two('GBIF pide citar cada descarga con su DOI; para el artículo final, repite la descarga en su portal con los mismos filtros. Estos son los conjuntos que aportaron registros depurados:', 'GBIF asks for each download to be cited with its DOI; for the final paper, repeat the download on its portal with the same filters. These are the datasets that contributed cleaned records:'));
      tail += table([{ label: two('Conjunto', 'Dataset'), get: d => esc(d.name || d.key) }, { label: two('Clave', 'Key'), get: d => (d.key ? `<a href="https://www.gbif.org/dataset/${esc(d.key)}">${esc(d.key.slice(0, 8))}…</a>` : '—') }, { label: two('Licencia', 'Licence'), get: d => esc(String(d.license || '').replace(/^https?:\/\/creativecommons.org\/(licenses|publicdomain)\//, '').replace(/\/legalcode$/, '')) }, { label: two('Registros', 'Records'), num: true, key: 'n' }], ds.slice(0, 60), two('Conjuntos de datos con registros en el estudio', 'Datasets with records in the study'));
    }
    tail += `<h2>${two('Referencias', 'References')}</h2><ol class="refs">${refs.map(r => `<li>${r[2]}</li>`).join('')}</ol>`;
    tail += `<h2>${two('Cómo citar el programa', 'How to cite the software')}</h2>` + p(two(`Barrera-Guzmán, L.Á. (2026). PollinationPro: plataforma en el navegador para el análisis de plantas, polinizadores y su solapamiento con datos de presencia (versión ${APP_VERSION}) [software]. Zenodo. https://doi.org/10.5281/zenodo.23004694`, `Barrera-Guzmán, L.Á. (2026). PollinationPro: a browser-based platform for analysing plants, pollinators and their overlap with occurrence data (Version ${APP_VERSION}) [Computer software]. Zenodo. https://doi.org/10.5281/zenodo.23004694`));
    if (o.appendix !== false) tail += `<h2>${two('Anexo: registro de cálculo', 'Appendix: calculation record')}</h2><pre>${esc(JSON.stringify(params(), null, 1))}</pre>`;
    const summary = summaryLines().map(s => `<li>${s}</li>`).join('');
    return `<!DOCTYPE html><html lang="${I18N.lang}"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>${esc(title)}</title><style>
      body{font-family:system-ui,-apple-system,"Segoe UI",Arial,sans-serif;max-width:900px;margin:0 auto;padding:28px 22px 60px;color:#1a2419;line-height:1.55;background:#fff}
      h1{font-size:1.7rem;margin:0 0 4px}h2{font-size:1.2rem;margin:30px 0 8px;border-bottom:2px solid #2e7d4f;padding-bottom:4px;color:#1f5a36}
      .meta{color:#5d6b5a;font-size:.9rem}.summary{background:#f3f7ef;border:1px solid #dde5d6;border-radius:10px;padding:12px 18px}
      table{border-collapse:collapse;width:100%;margin:12px 0 18px;font-size:.84rem}caption{text-align:left;font-weight:600;margin-bottom:4px}
      th,td{border-bottom:1px solid #dde5d6;padding:4px 6px;text-align:left}th{background:#f3f7ef}td.num,th.num{text-align:right;font-variant-numeric:tabular-nums}
      figure{margin:16px 0}.fig svg{width:100%;height:auto}figcaption{font-size:.84rem;color:#5d6b5a}
      .kv{display:grid;grid-template-columns:max-content 1fr;gap:2px 14px}.kv dt{font-weight:600}.kv dd{margin:0}
      .warn{background:#fff4e0;border-left:4px solid #d99a1e;padding:8px 12px}.refs li{margin-bottom:4px;font-size:.88rem}pre{font-size:.72rem;background:#f5f7f2;padding:10px;overflow:auto;white-space:pre-wrap}
      @media print{h2{page-break-after:avoid}figure,table{page-break-inside:avoid}}
    </style></head><body><h1>${esc(title)}</h1><p class="meta">${o.author ? esc(o.author) + ' · ' : ''}${two('Generado con PollinationPro', 'Generated with PollinationPro')} ${APP_VERSION} · ${new Date().toISOString().slice(0, 10)}</p>
    <div class="summary"><b>${two('Resumen', 'Summary')}</b><ul>${summary}</ul></div>${body}${tail}</body></html>`;
  }

  function summaryLines() {
    const L = [];
    if (state.clean) L.push(two(`${f0(state.clean.records.length)} registros depurados de ${new Set(state.clean.records.map(r => r.unit)).size} unidades.`, `${f0(state.clean.records.length)} cleaned records of ${new Set(state.clean.records.map(r => r.unit)).size} units.`));
    if (state.cooc) { const P = state.cooc.res.pairs, v = x => (state.cooc.opt.adjust ? x.verdictAdj : x.verdict); L.push(two(`Coocurrencia: ${P.filter(x => v(x) === 'positive').length} de ${P.length} pares coinciden más de lo esperado.`, `Co-occurrence: ${P.filter(x => v(x) === 'positive').length} of ${P.length} pairs coincide more than expected.`)); }
    if (state.pheno && state.pheno.pairs.length) { const b = state.pheno.pairs.slice().sort((a, c) => c.D - a.D)[0]; L.push(two(`Mayor solapamiento fenológico: ${it(b.plant)} × ${it(b.visitor)} (D = ${f2(b.D)}).`, `Highest phenological overlap: ${it(b.plant)} × ${it(b.visitor)} (D = ${f2(b.D)}).`)); }
    if (state.niche && state.niche.pair) L.push(two(`Nicho: D = ${f3(state.niche.pair.D)} entre ${it(state.niche.pair.plant)} y ${it(state.niche.pair.visitor)}.`, `Niche: D = ${f3(state.niche.pair.D)} between ${it(state.niche.pair.plant)} and ${it(state.niche.pair.visitor)}.`));
    if (state.sdm) { const A = state.sdm.area; L.push(two(`Desajuste: ${pc(A[1] / Math.max(1, A[1] + A[3]))} del área idónea de ${it(state.sdm.plant)} sin visitante potencial.`, `Mismatch: ${pc(A[1] / Math.max(1, A[1] + A[3]))} of ${it(state.sdm.plant)}'s suitable area without a potential visitor.`)); }
    if (state.network) L.push(two(`Red: ${state.network.plants} plantas, ${state.network.visitors} visitantes, H₂′ = ${f3(state.network.H2p)}.`, `Network: ${state.network.plants} plants, ${state.network.visitors} visitors, H₂′ = ${f3(state.network.H2p)}.`));
    return L;
  }

  /* ---------------- the calculation record ---------------- */
  function params() {
    return {
      app: 'PollinationPro', version: APP_VERSION, date: new Date().toISOString(),
      taxa: state.taxa.map(t => ({ name: t.name, role: t.role, gbifKey: t.key, accepted: t.resolved ? t.resolved.scientificName : null })),
      download: window.B2 ? B2.filters() : null, fetchMeta: state.fetchMeta,
      cleaning: state.clean ? state.clean.params : null,
      map: window.MapStudio ? (() => { const s = Object.assign({}, MapStudio.get()); delete s.units; return s; })() : null,
      cooccurrence: state.cooc ? state.cooc.opt : null,
      phenology: state.pheno ? state.pheno.opt : null,
      niche: state.niche ? { layers: state.niche.layers, bg: state.niche.bg, bufferKm: state.niche.bufferKm, corrected: state.niche.corrected, nRep: state.niche.pair && state.niche.pair.nRep } : null,
      distribution: state.sdm ? { kind: state.sdm.kind, rule: state.sdm.rule, bgMode: state.sdm.bgMode, layers: state.sdm.layers, plant: state.sdm.plant, visitors: state.sdm.visitors, future: state.sdm.future ? state.sdm.future.files : null } : null,
      network: state.network ? state.network.opt : null,
    };
  }

  /* ---------------- the tables as .csv ---------------- */
  function csvs() {
    const out = [];
    const add = (name, rows, cols) => { if (rows && rows.length) out.push({ name: 'cuadros/' + name, text: TableIO.toCSV(rows, cols) }); };
    if (state.clean) add('registros_depurados.csv', state.clean.records, ['id', 'src', 'role', 'unit', 'name', 'origName', 'lat', 'lon', 'unc', 'elev', 'cc2', 'stName', 'y', 'm', 'd', 'basis', 'inst', 'dataset', 'datasetKey', 'license', 'gbifKey']);
    if (state.clean) add('registros_quitados.csv', state.clean.dropped, ['id', 'src', 'role', 'unit', 'name', 'lat', 'lon', 'y', 'm', 'd', 'basis', 'removedBy']);
    if (state.cooc) add('coocurrencia_pares.csv', state.cooc.res.pairs.map(p => ({ plant: p.plant, visitor: p.visitor, N: p.N, n1: p.n1, n2: p.n2, shared: p.shared, expected: p.exp, ses: p.ses, p_less: p.pLe, p_more: p.pGe, p_adj: p.pAdj, verdict: p.verdict, verdict_adj: p.verdictAdj, jaccard: p.jaccard, cover: p.cover })));
    if (state.pheno) { add('fenologia_unidades.csv', state.pheno.units.map(u => ({ unit: u.unit, role: u.role, n: u.n, mean_doy: u.meanDoy, R: u.R, sd_days: u.sdDays, rayleigh_p: u.p }))); add('fenologia_pares.csv', state.pheno.pairs.map(p => ({ plant: p.plant, visitor: p.visitor, D: p.D, I: p.I, O: p.O, lag: p.lag, ww_p: p.wwP }))); }
    if (state.niche) add('nicho_pares.csv', state.niche.matrix);
    if (state.sdm) add('distribucion_evaluacion.csv', Object.entries(state.sdm.units).map(([u, x]) => Object.assign({ unit: u }, x)));
    if (state.network) add('red_especies.csv', state.network.species.plants.concat(state.network.species.visitors));
    add('conjuntos_gbif.csv', datasets());
    return out;
  }

  Object.assign(Report, { build, csvs, params, summary: summaryLines, datasets });
  window.Report = Report;
})();
